
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-distributed
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
  destination:
    namespace: lgtm-distributed
    server: https://kubernetes.default.svc
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: lgtm-distributed
      targetRevision: "2.1.0"
      helm:
        valueFiles:
          - $values/lgtm/values.yaml
    - repoURL: "https://github.com/holdeneoneal/o11y.git"
      targetRevision: otel
      ref: values
